/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.bioscomputacion.Formularios;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicMenuBarUI;

/**
 *
 * @author braya
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/ar/com/bioscomputacion/Iconos/forms.png")).getImage());
        menuPrincipal.setOpaque(true);
        menuPrincipal.setUI(new BasicMenuBarUI() {
            public void paint(Graphics g, JComponent c) {
                g.setColor(new java.awt.Color(51, 84, 111));
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }
        });
        txtCod_usuario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        rSLabelHora1 = new rojeru_san.RSLabelHora();
        jLabel2 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCod_usuario = new javax.swing.JTextField();
        menuPrincipal = new javax.swing.JMenuBar();
        menuVentas = new javax.swing.JMenu();
        menuPlanilla = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuReparaciones = new javax.swing.JMenu();
        menuPersona = new javax.swing.JMenu();
        menuCtaCte = new javax.swing.JMenu();
        menuCaja = new javax.swing.JMenu();
        menuItemApertura = new javax.swing.JMenuItem();
        menuItemCierre = new javax.swing.JMenuItem();
        menuProducto = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bios Computacion - SERVICES Y VENTAS");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/Imagenes/Logo-grande.png"))); // NOI18N

        rSLabelHora1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelHora1.setFont(new java.awt.Font("Roboto Bold", 3, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Usuario:");

        lbNombre.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(255, 255, 255));
        lbNombre.setText("NOMBRE DEL USUARIO");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Tipo:");

        lbTipo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lbTipo.setForeground(new java.awt.Color(255, 255, 255));
        lbTipo.setText("TIPO DEL USUARIO");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Hora:");

        deskPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskPrincipal.setLayer(rSLabelHora1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskPrincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskPrincipal.setLayer(lbNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskPrincipal.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskPrincipal.setLayer(lbTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskPrincipal.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskPrincipal.setLayer(txtCod_usuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deskPrincipalLayout = new javax.swing.GroupLayout(deskPrincipal);
        deskPrincipal.setLayout(deskPrincipalLayout);
        deskPrincipalLayout.setHorizontalGroup(
            deskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deskPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCod_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deskPrincipalLayout.createSequentialGroup()
                        .addGap(0, 242, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(248, 248, 248))))
        );
        deskPrincipalLayout.setVerticalGroup(
            deskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deskPrincipalLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(deskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(deskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lbNombre)
                        .addComponent(jLabel4)
                        .addComponent(lbTipo)
                        .addComponent(jLabel5)
                        .addComponent(txtCod_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deskPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        menuPrincipal.setBackground(new java.awt.Color(47, 110, 164));
        menuPrincipal.setForeground(new java.awt.Color(47, 110, 164));

        menuVentas.setForeground(new java.awt.Color(255, 255, 255));
        menuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/MenuIcons/venta.png"))); // NOI18N
        menuVentas.setText("VENTA");
        menuVentas.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        menuPrincipal.add(menuVentas);

        menuPlanilla.setBackground(new java.awt.Color(51, 84, 111));
        menuPlanilla.setForeground(new java.awt.Color(255, 255, 255));
        menuPlanilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/MenuIcons/planilla_control.png"))); // NOI18N
        menuPlanilla.setText("PLANILLA DE CONTROL");
        menuPlanilla.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        menuPlanilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPlanillaMouseClicked(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setBackground(new java.awt.Color(51, 84, 111));
        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/MenuItemIcon/planilla_diaria.png"))); // NOI18N
        jMenuItem1.setText("PLANILLA DIARIA");
        jMenuItem1.setOpaque(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuPlanilla.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem2.setBackground(new java.awt.Color(51, 84, 111));
        jMenuItem2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/MenuItemIcon/planilla_mensual.png"))); // NOI18N
        jMenuItem2.setText("PLANILLA MENSUAL");
        jMenuItem2.setOpaque(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuPlanilla.add(jMenuItem2);

        menuPrincipal.add(menuPlanilla);

        menuReparaciones.setForeground(new java.awt.Color(255, 255, 255));
        menuReparaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/MenuIcons/reparaciones.png"))); // NOI18N
        menuReparaciones.setText("REPARACIONES");
        menuReparaciones.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        menuPrincipal.add(menuReparaciones);

        menuPersona.setForeground(new java.awt.Color(255, 255, 255));
        menuPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/MenuIcons/persona.png"))); // NOI18N
        menuPersona.setText("PERSONA");
        menuPersona.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        menuPrincipal.add(menuPersona);

        menuCtaCte.setForeground(new java.awt.Color(255, 255, 255));
        menuCtaCte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/MenuIcons/cuenta_corriente.png"))); // NOI18N
        menuCtaCte.setText("CTA. CTE");
        menuCtaCte.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        menuPrincipal.add(menuCtaCte);

        menuCaja.setForeground(new java.awt.Color(255, 255, 255));
        menuCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/MenuIcons/caja.png"))); // NOI18N
        menuCaja.setText("CAJA");
        menuCaja.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N

        menuItemApertura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemApertura.setBackground(new java.awt.Color(51, 84, 111));
        menuItemApertura.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        menuItemApertura.setForeground(new java.awt.Color(255, 255, 255));
        menuItemApertura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/MenuItemIcon/apertura.png"))); // NOI18N
        menuItemApertura.setText("APERTURA CAJA");
        menuItemApertura.setOpaque(true);
        menuItemApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAperturaActionPerformed(evt);
            }
        });
        menuCaja.add(menuItemApertura);

        menuItemCierre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemCierre.setBackground(new java.awt.Color(51, 84, 111));
        menuItemCierre.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        menuItemCierre.setForeground(new java.awt.Color(255, 255, 255));
        menuItemCierre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/MenuItemIcon/cierre.png"))); // NOI18N
        menuItemCierre.setText("CIERRE CAJA");
        menuItemCierre.setOpaque(true);
        menuItemCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCierreActionPerformed(evt);
            }
        });
        menuCaja.add(menuItemCierre);

        menuPrincipal.add(menuCaja);

        menuProducto.setForeground(new java.awt.Color(255, 255, 255));
        menuProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/MenuIcons/producto.png"))); // NOI18N
        menuProducto.setText("PRODUCTOS");
        menuProducto.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        menuPrincipal.add(menuProducto);

        menuSalir.setForeground(new java.awt.Color(255, 255, 255));
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/bioscomputacion/MenuIcons/cerrar_sesion.png"))); // NOI18N
        menuSalir.setText("CERRAR SESIÓN");
        menuSalir.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuSalir);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed

    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        this.dispose();

        FrmLogin form = new FrmLogin();
        form.setVisible(true);
    }//GEN-LAST:event_menuSalirMouseClicked

    private void menuPlanillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPlanillaMouseClicked
  
    }//GEN-LAST:event_menuPlanillaMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmPlanillaDeControl form = new FrmPlanillaDeControl();

        deskPrincipal.add(form);
        Dimension desktopSize = deskPrincipal.getSize();
        Dimension FrameSize = form.getSize();

        form.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        form.setVisible(true);

        form.setClosable(true);
        form.setIconifiable(false);
        form.txtNombrepersona.setText(this.lbNombre.getText());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAperturaActionPerformed
        FrmAperturaCaja form = new FrmAperturaCaja();

        deskPrincipal.add(form);
        Dimension desktopSize = deskPrincipal.getSize();
        Dimension FrameSize = form.getSize();

        form.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        form.setVisible(true);

        form.setClosable(true);
        form.setIconifiable(false);
        form.txtEmpleado.setText(this.lbNombre.getText());
        form.txtCod_usuario.setText(this.txtCod_usuario.getText());
    }//GEN-LAST:event_menuItemAperturaActionPerformed

    private void menuItemCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCierreActionPerformed
        FrmCierreCaja form = new FrmCierreCaja();

        deskPrincipal.add(form);
        Dimension desktopSize = deskPrincipal.getSize();
        Dimension FrameSize = form.getSize();

        form.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        form.setVisible(true);

        form.setClosable(true);
        form.setIconifiable(false);
        form.txtEmpleado.setText(this.lbNombre.getText());
        form.txtCod_usuario.setText(this.txtCod_usuario.getText());
    }//GEN-LAST:event_menuItemCierreActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane deskPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JLabel lbNombre;
    public javax.swing.JLabel lbTipo;
    public static javax.swing.JMenu menuCaja;
    public static javax.swing.JMenu menuCtaCte;
    public static javax.swing.JMenuItem menuItemApertura;
    public static javax.swing.JMenuItem menuItemCierre;
    public static javax.swing.JMenu menuPersona;
    public static javax.swing.JMenu menuPlanilla;
    private javax.swing.JMenuBar menuPrincipal;
    public static javax.swing.JMenu menuProducto;
    public static javax.swing.JMenu menuReparaciones;
    private javax.swing.JMenu menuSalir;
    public static javax.swing.JMenu menuVentas;
    private rojeru_san.RSLabelHora rSLabelHora1;
    public javax.swing.JTextField txtCod_usuario;
    // End of variables declaration//GEN-END:variables
}
